version: 2.1

jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - run:
          name: Install LFTP
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;
      - checkout
      - run:
          name: Send Via SFTP
          command: lftp sftp://$SFTP_USER:$SFTP_PASSWORD@$SFTP_HOST -e "mirror -v -R --exclude .git/ --exclude .circleci/ --exclude ./db_admin --exclude ./ ./; quit"

workflows:
  test:
    jobs:
      - build:
          filters:
            tags:
              only: master