version: 2.1

jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - run:
          name: Install LFTP
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;
      - checkout
      - run:
          name: Send Via SFTP
          command: lftp sftp://$SFTP_USER:$SFTP_PASSWORD@$SFTP_HOST -e "mirror -v -R --delete-excluded --delete-first --include .*\.php --exclude .git/ --exclude db_admin/ --target-directory ./ftp_test3; quit"

workflows:
  test:
    jobs:
      - build:
          filters:
            tags:
              only: master